---
- hosts: all
  become: True

  tasks:
     - name: Download Percona Repo
       get_url: 
          url: 'https://repo.percona.com/apt/percona-release_latest.xenial_all.deb'
          dest: '/tmp/percona-release_latest.xenial_all.deb'

     - name: Install Percona Repo
       apt:
          deb: '/tmp/percona-release_latest.xenial_all.deb'

     - name: update apt chache
       apt:   
          update_cache: yes

     - name: Install Percona Server
       apt:
         name: "{{ item }}" 
         state: present
         force: yes 
       vars:
         item:
            - percona-server-common-5.7
            - percona-server-client-5.7
            - percona-server-server-5.7
       environment:
          DEBIAN_FRONTEND: noninteractive
       notify:
          - start mysql

     - name: Install Percona Toolkit
       apt:
         name: percona-toolkit
         state: present
         force: yes

     - name: Install ProxySQL 
       apt: 
         name: proxysql
         state: present
         force: yes
       notify:
         - start proxysql

  handlers:
     - name: start mysql
       service:
             name: mysql
             state: restarted
             enabled: yes

     - name: start proxysql
       service: 
             name: proxysql 
             state: restarted 
             enabled: yes


