---
- hosts: all
  become: True

  tasks:
     - name: update apt cache
       apt:
          update_cache: yes
          cache_valid_time: 86400

     - name: Add Percona apt signing key
       apt_key: 
          keyserver: keys.gnupg.net 
          id: 8507EFA5 
          state: present

     - name: Install/Add Percona Repo
       apt_repository: 
          repo: 'deb https://repo.percona.com/apt trusty main'
          state: present

     - name: Install Percona Server
       apt:
         name: "{{ item }}" 
         state: present
         update_cache: yes
         force: yes 
       vars:
         item:
            - percona-server-common-5.7
            - percona-server-client-5.7
            - percona-server-server-5.7
       environment:
          DEBIAN_FRONTEND: noninteractive
       notify:
          - start mysql

  handlers:
     - name: start mysql
       service:
             name: mysql
             state: restarted
             enabled: yes
