---
- hosts: all
  become: True

  tasks:
     - name: Download Percona Repo
       get_url: 
          url: 'https://repo.percona.com/apt/percona-release_latest.xenial_all.deb'
          dest: '/tmp/percona-release_latest.xenial_all.deb'

     - name: Install Percona Repo
       apt:
          deb: '/tmp/percona-release_latest.xenial_all.deb'

     - name: update apt chache
       apt:   
          update_cache: yes

     - name: Add hosts inside /etc/hosts
       lineinfile:
         path: /etc/hosts
         state: present
         line: "{{ item }}"
       with_items:
         - 192.168.135.111  mysql1  mysql1
         - 192.168.135.112  mysql2  mysql2
         - 192.168.135.113  mysql3  mysql3

     - name: Install Percona Server
       apt:
         name: "{{ item }}" 
         state: present
         force: yes 
       vars:
         item:
            - percona-server-common-5.7
            - percona-server-client-5.7
            - percona-server-server-5.7
       environment:
          DEBIAN_FRONTEND: noninteractive

     - name: configure my.cnf
       template: 
         src: mysql1.my.cnf.j2 
         dest: /etc/mysql/my.cnf

     - name: restart mysql
       service:
             name: mysql
             state: restarted
             enabled: yes

     - name: Install Percona Toolkit
       apt:
         name: percona-toolkit
         state: present
         force: yes

     - name: Install dependency 
       apt:
         name: python2.7-mysqldb
         state: present

     - name : Create repl user 
       mysql_user:
         name: repl
         password: repl
         host: '%'
         priv: "*.*:REPLICATION CLIENT,REPLICATION SLAVE"
         state: present


