---
- hosts: all
  become: True

  tasks:
     - name: Install/Add Percona Repo
       apt_repository: 
          repo: 'deb https://repo.percona.com/apt trusty main'
          state: present

     - name: Install Percona Server
       apt:
          name: percona-server-server-5.7
          state: present
       notify:
          - start mysql

  handlers:
     - name: start mysql
       service:
             name: mysql
             state: restarted
             enabled: yes
